[project]
authors = ["Samuel Ibarra <Samuel.E.Ibarra@dell.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "https://repo.prefix.dev/conda-forge"]
description = "Series/Parallel Runner"
name = "move"
platforms = ["linux-64", "osx-arm64"]
version = "0.2.0"

[tasks]
examples = { depends-on = ["defaultable_examples", "immutable_examples", "message_examples", "mutable_examples"] }
mutable_examples = "mojo examples/mutable_examples.mojo"
immutable_examples = "mojo examples/immutable_examples.mojo"
defaultable_examples = "mojo examples/defaultable_examples.mojo"
message_examples = "mojo examples/message_examples.mojo"
test = "mojo test --diagnose-missing-doc-strings --validate-doc-strings"

[dependencies]
max = "*"
