[project]
authors = ["Samuel Ibarra <Samuel.E.Ibarra@dell.com>"]
channels = ["https://repo.prefix.dev/conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "tne_campaigns"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
engine = "mojo run src/tne_campaigns/main.mojo"

[dependencies]
max = "*"
