[project]
authors = ["Samuel Ibarra <Samuel.E.Ibarra@dell.com>"]
channels = ["https://repo.prefix.dev/conda-forge", "https://conda.modular.com/max-nightly"]
description = "Series/Parallel Runner"
name = "move"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
example = "mojo run src/examples.mojo"

[dependencies]
max = "*"
