# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: "strata"
  version: "0.0.1"
  max_version: "=25.5"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: .
  use_gitignore: true

build:
  number: 0
  files:
    - strata/**/*.mojo
  script:
    - mojo package strata -o ${{ PREFIX }}/lib/mojo/${{ name }}.mojopkg

requirements:
  host:
    - max ${{ max_version }}
  run:
    - ${{ pin_compatible('max') }}

# tests:
#   - script:
#       - if: unix
#         then:
#           - mojo run tests.mojo

#     requirements:
#       run:
#         - max=25.3

#     files:
#       recipe:
#         - tests.mojo

about:
  homepage: https://github.com/sibarras/${{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Parallel executor on top of mojo asyncrt.
  repository: https://github.com/sibarras/${{ name }}

extra:
  project_name: ${{ name }}
  maintainers:
    - sibarras
