[workspace]
authors = ["Samuel Ibarra <ing.samuelibarra@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "https://repo.prefix.dev/conda-forge",
]
description = "Series/Parallel Runner Examples"
name = "strata examples"
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
strata = { path = ".." }

[tasks]
# Examples
examples = { depends-on = [
    "type_examples",
    "immutable_examples",
    "message_examples",
    "mutable_examples",
    "unsafe_examples",
    "async_immutable_task_examples",
    "async_mutable_task_examples",
    "generic_examples",
] }
async_immutable_task_examples = "mojo async_immutable_task_examples.mojo"
async_mutable_task_examples = "mojo async_mutable_task_examples.mojo"
generic_examples = "mojo generic_examples.mojo"
mutable_examples = "mojo mutable_examples.mojo"
unsafe_examples = "mojo unsafe_examples.mojo"
immutable_examples = "mojo immutable_examples.mojo"
type_examples = "mojo type_examples.mojo"
message_examples = "mojo message_examples.mojo"