[workspace]
# authors = ["Samuel Ibarra <Samuel.E.Ibarra@dell.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "https://repo.prefix.dev/conda-forge",
]
# description = "Series/Parallel Runner Examples"
# name = "move examples"
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
# max = "*"
strata = { path = ".." }
